name: "いつも成功"
on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  success:
    runs-on: ubuntu-latest
    name: "成功"
    steps:
      - name: "ステップ echo"
        run: "echo '成功'"

      - name: "ステップ sleep"
        run: sleep 60

      - name: "ステップ success"
        run: "echo success"
